### ISSUE TITLE
不同node上的容器之间ping不通

### ISSUE THREAD

**Issue by ThreeGoldStone** [yonyoucloud/install_k8s#11]
![image](https://user-images.githubusercontent.com/7277677/46781409-1353b500-cd54-11e8-924d-1b0f9ff1b71c.png)

**Comment by bishenghua** [comment]
安装是否有报错？检查一下calico容器是否都ok，另外，不建议宿主机用192.168网段，因为这个用在了集群IP上，最好是10网段，或者172网段（但172网段不要用172.30，这个用在了容器IP上）

**Comment by ThreeGoldStone** [comment]
谢谢
这个问题我已经解决了，但错误的具体原因我还没弄清楚，大概知道的是node节点上的calico网络的转发路由没有启动或生效，为什么会没有我还不清楚，猜测可能和我在安装之前改过网卡名称（esn192 > eth0） 有关
所以：
我今天又弄了几个新机器没有改网卡，只是把你脚本里面的eth0 改为我的网卡名称ens192 装好就ok了
