### ISSUE TITLE
请问第二步的二进制包的格式是怎样的？能否支持官方的包？

### ISSUE THREAD

**Issue by blademainer** [yonyoucloud/install_k8s#15]
例如：我的vps是海外的，可以直接在github下载就好了，好像直接下载下来的格式跟百度云盘格式不一样（没有云盘会员，表示下载很慢）

**Comment by bishenghua** [comment]
> 例如：我的vps是海外的，可以直接在github下载就好了，好像直接下载下来的格式跟百度云盘格式不一样（没有云盘会员，表示下载很慢）

这些二进制包是通过k8s源码编译出来的，你也可以自己clone下源码来编译。百度云盘确实比较慢，我也没有其他地方可以放~
