### ISSUE TITLE
总共有4个节点，但./calicoctl node status 只能看到一个

### ISSUE THREAD

**Issue by ThreeGoldStone** [yonyoucloud/install_k8s#16]
![image](https://user-images.githubusercontent.com/7277677/54505658-ba77f080-4973-11e9-9009-1d159c8e02a3.png)

**Comment by ThreeGoldStone** [comment]
calico网络节点只有一个能连上主节点，

**Comment by ThreeGoldStone** [comment]
这个问题我解决了，主要问题是我的node节点机器的hostname都是一样的，calico/node取名字的时候都是一样的，然后往etcd里放不进去，就出现了上面的情况，
解决方案：修改各个node的hostname，然后删除/var/lib/calico/hostname的缓存，最后删除caliconode的pod，等待重启就好了

**Comment by bishenghua** [comment]
> 这个问题我解决了，主要问题是我的node节点机器的hostname都是一样的，calico/node取名字的时候都是一样的，然后往etcd里放不进去，就出现了上面的情况，
> 解决方案：修改各个node的hostname，然后删除/var/lib/calico/hostname的缓存，最后删除caliconode的pod，等待重启就好了

👍
