### ISSUE TITLE
等待所有节点calico容器正常运行(66s)(3 = 1)

### ISSUE THREAD

**Issue by caijiaolong** [yonyoucloud/install_k8s#18]
kubectl get pods -o wide -n kube-system | grep calico | grep Running | wc -l
等待所有节点calico容器正常运行(66s)(3 = 1)

calico-kube-controllers-5975bbd797-f6nx8   1/1     Running            0          2m7s   10.0.0.5   10.0.0.5   <none>           <none>
calico-node-5tm79                          1/2     CrashLoopBackOff   4          2m7s   10.0.0.5   10.0.0.5   <none>           <none>

这个节点一直失败，而且为什么是三个判断而不是两个啊

**Comment by caijiaolong** [comment]
已解决，hostname必须不带_

**Comment by xiemey** [comment]
这是怎么解决的，可以具体说一下嘛

**Comment by bishenghua** [comment]
https://blog.csdn.net/wanghuiict/article/details/70038140 参考一下这个，calico不允许hostname有下划线的。
