### ISSUE TITLE
kube-apiserver external host was not specified

### ISSUE THREAD

**Issue by adangadang** [yonyoucloud/install_k8s#24]
Nov 07 19:57:17 k8s1 systemd[1]: Starting Kubernetes API Server...
Nov 07 19:57:17 k8s1 kube-apiserver[5202]: I1107 19:57:17.182892    5202 server.go:557] external host was not specified, using 192.168.1.81
Nov 07 19:57:17 k8s1 kube-apiserver[5202]: I1107 19:57:17.183249    5202 server.go:146] Version: v1.13.3-1+e85e6a94bac0e4

**Comment by adangadang** [comment]
centos7.7

**Comment by bishenghua** [comment]
你的ip是怎么配置的呢？
