### ISSUE TITLE
/bin/sh: line 0: cd: source/needbin: No such file or directory

### ISSUE THREAD

**Issue by ghost** [yonyoucloud/install_k8s#31]
[localhost] local: cd source/needbin && tar zcvf needbin.gz usr
/bin/sh: line 0: cd: source/needbin: No such file or directory

Fatal error: local() encountered an error (return code 1) while executing 'cd source/needbin && tar zcvf needbin.gz usr'

Aborting.
[root@localhost install_k8s]# cd source/needbin

![image](https://user-images.githubusercontent.com/21974344/71469608-b3381a00-2804-11ea-8aeb-e9d1ecc72db3.png)

**Comment by bishenghua** [comment]
下载的二进制文件包应该包括一下文件：

**Comment by lifa1225** [comment]
谢谢，对了，我用的是v1.16.3.1得安装，单机版，但是发现dashboard一直无法打开，curl得时候refuse，30000端口是监听着，请问有办法一键重启所有k8s服务吗？

**Comment by bishenghua** [comment]
dashboard: https://ip:30000 可能会涉及自检证书信任问题
