### ISSUE TITLE
大佬：如果需要支持k8s 1.19版本，需要更改什么文件

### ISSUE THREAD

**Issue by arraycto** [yonyoucloud/install_k8s#32]
大佬：如果需要支持k8s 1.19版本，需要更改什么文件

**Comment by arraycto** [comment]
请问如何升级

**Comment by bishenghua** [comment]
从k8s源码中编译出下面几个二进制文件，替换一下就行了。
source/master/usr/bin/kube-apiserver
source/master/usr/bin/kube-controller-manager
source/master/usr/bin/kube-scheduler
source/node/usr/bin/kube-proxy
source/node/usr/bin/kubelet

source/needbin/usr/local/bin/kubectl
source/needbin/usr/local/bin/kubeadm
source/needbin/usr/local/bin/kubemark
