### ISSUE TITLE
[开始]启动所有服务 报错

### ISSUE THREAD

**Issue by yiwenshuo** [yonyoucloud/install_k8s#4]
{2018年 01月 30日 星期二 11:17:24 CST}[开始]启动所有服务.............................
[10.103.70.120:22] Executing task 'service_etcd'
[10.103.70.121:22] Executing task 'service_etcd'
[10.103.70.121:22] run: systemctl start etcd ; echo "" > /dev/null
[10.103.70.120:22] run: systemctl start etcd ; echo "" > /dev/null
[10.103.70.120:22] out: Job for etcd.service failed because the control process exited with error code. See "systemctl status etcd.service" and "journalctl -xe" for details.
[10.103.70.120:22] out: 

[10.103.70.120:22] run: iptables -P FORWARD ACCEPT
[localhost] local: etcdctl --ca-file=source/etcd/etc/etcd/ssl/ca.pem --cert-file=source/etcd/etc/etcd/ssl/etcd.pem --key-file=source/etcd/etc/etcd/ssl/etcd-key.pem --endpoints=https://10.103.70.122:2379 set /esn.com/network/config '{"Network":"172.30.0.0/16","SubnetLen":25,"Backend":{"Type":"vxlan"}}'
Error:  dial tcp 10.103.70.122:2379: getsockopt: connection refused

Fatal error: local() encountered an error (return code 2) while executing 'etcdctl --ca-file=source/etcd/etc/etcd/ssl/ca.pem --cert-file=source/etcd/etc/etcd/ssl/etcd.pem --key-file=source/etcd/etc/etcd/ssl/etcd-key.pem --endpoints=https://10.103.70.122:2379 set /esn.com/network/config '{"Network":"172.30.0.0/16","SubnetLen":25,"Backend":{"Type":"vxlan"}}''

Aborting.

**Comment by yiwenshuo** [comment]
The connection to the server 10.103.70.123:6443 was refused - did you specify the right host or port?

**Comment by yiwenshuo** [comment]
![image](https://user-images.githubusercontent.com/22519964/35546610-e66751c6-05af-11e8-9618-3c9b413af2a8.png)

**Comment by yiwenshuo** [comment]
[root@master ~]# systemctl status etcd.service
● etcd.service - Etcd Server
   Loaded: loaded (/usr/lib/systemd/system/etcd.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since 二 2018-01-30 11:17:27 CST; 6min ago
  Process: 4977 ExecStart=/usr/bin/etcd --name=${ETCD_NAME} --data-dir=${ETCD_DATA_DIR} --listen-client-urls=${ETCD_LISTEN_CLIENT_URLS} --listen-peer-urls=${ETCD_LISTEN_PEER_URLS} --advertise-client-urls=${ETCD_ADVERTISE_CLIENT_URLS} --initial-cluster-token=${ETCD_INITIAL_CLUSTER_TOKEN} --initial-cluster=${ETCD_INITIAL_CLUSTER} --initial-cluster-state=${ETCD_INITIAL_CLUSTER_STATE} --initial-advertise-peer-urls=${ETCD_LISTEN_PEER_URLS} --cert-file=/etc/etcd/ssl/etcd.pem --key-file=/etc/etcd/ssl/etcd-key.pem --peer-cert-file=/etc/etcd/ssl/etcd.pem --peer-key-file=/etc/etcd/ssl/etcd-key.pem --trusted-ca-file=/etc/etcd/ssl/ca.pem --peer-trusted-ca-file=/etc/etcd/ssl/ca.pem (code=exited, status=1/FAILURE)
 Main PID: 4977 (code=exited, status=1/FAILURE)

**Comment by bishenghua** [comment]
尝试一下新版本呢

**Comment by zuohuadong** [comment]
@bishenghua +1 
centos 7.4 出错
升级到 7.5 依然出错
