### ISSUE TITLE
不能pull下来

### ISSUE THREAD

**Issue by cwchen** [yonyoucloud/install_k8s#5]
提示：
batch response: This repository is over its data quota. Purchase more data packs to restore access.  
能把二进制包放到其他的地方么？比如百度云盘等。

**Comment by bishenghua** [comment]
可以翻墙pull试试，每次都放百度云盘麻烦一些

**Comment by cwchen** [comment]
用国外的服务器试了下，不行，不过看提示，应该是要购买github的data packs才行 @bishenghua

**Comment by bishenghua** [comment]
我打包一下放百度网盘一份吧。

**Comment by cwchen** [comment]
收到，赶紧试一下，非常感谢
