### ISSUE TITLE
安装依赖报错，install_docker报错

### ISSUE THREAD

**Issue by zhaop33** [yonyoucloud/install_k8s#9]
![image](https://user-images.githubusercontent.com/27794742/42550038-d23c56fc-8501-11e8-8230-71b3a8b7709f.png)

我安装时报错，所有IP设置的是同一台centos7主机，vip设置的两个同一网段的不同IP，网络名称也改了。请问还有哪些地方要改的吗

**Comment by bishenghua** [comment]
你的是哪个版本，我用CentOS Linux release 7.4.1708 (Core) 和7.3都是ok的，fu'zhi复制出这个命令来执行一下看看呢。
![image](https://user-images.githubusercontent.com/1465604/42630709-5703f030-860a-11e8-837d-bc756135d1fc.png)

**Comment by zhaop33** [comment]
![image](https://user-images.githubusercontent.com/27794742/42637183-08b09376-861d-11e8-9da0-21f02f5a0118.png)
我的是这个。。。

**Comment by bishenghua** [comment]
更新一下安装脚本，试试新版本吧，docker已经本地化了
